/**
 * CSS CUSTOM PROPERTIES GENERATOR
 * 
 * This module generates CSS custom properties from color palettes,
 * enabling dynamic theme switching through CSS variable updates.
 */

import { ColorPalette, ColorPaletteName } from './colorPalettes'

/**
 * CSS variable prefix for theme-related properties
 */
const CSS_VAR_PREFIX = '--theme'

/**
 * Flatten a nested object into CSS custom properties
 * @param obj - Nested object to flatten
 * @param prefix - Prefix for CSS variable names
 * @param separator - Separator between nested keys
 * @returns Object with flattened CSS custom properties
 */
function flattenObject(
  obj: Record<string, any>,
  prefix = '',
  separator = '-'
): Record<string, string> {
  const flattened: Record<string, string> = {}

  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}${separator}${key}` : key
    
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Recursively flatten nested objects
      Object.assign(flattened, flattenObject(value, newKey, separator))
    } else {
      // Add leaf values as CSS custom properties
      flattened[`--${CSS_VAR_PREFIX}-${newKey}`] = String(value)
    }
  }

  return flattened
}

/**
 * Generate CSS custom properties from a color palette
 * @param palette - Color palette to convert
 * @returns Object with CSS custom properties
 */
export function generateCSSVariables(palette: ColorPalette): Record<string, string> {
  return flattenObject(palette)
}

/**
 * Apply CSS variables to the document root
 * @param variables - CSS variables to apply
 */
export function applyCSSVariables(variables: Record<string, string>): void {
  const root = document.documentElement

  // Remove existing theme variables to avoid conflicts
  for (const prop of Array.from(document.documentElement.style)) {
    if (prop.startsWith(`--${CSS_VAR_PREFIX}-`)) {
      root.style.removeProperty(prop)
    }
  }

  // Apply new variables
  Object.entries(variables).forEach(([property, value]) => {
    root.style.setProperty(property, value)
  })
}

/**
 * Generate CSS custom properties and apply them to the document
 * @param palette - Color palette to apply
 */
export function applyColorPalette(palette: ColorPalette): void {
  const variables = generateCSSVariables(palette)
  applyCSSVariables(variables)
}

/**
 * Get CSS variable reference for use in Tailwind/CSS
 * @param path - Dot notation path to the color (e.g., 'interactive.primary')
 * @returns CSS var() reference
 */
export function getCSSVar(path: string): string {
  const cssVarName = `--${CSS_VAR_PREFIX}-${path.replace(/\./g, '-')}`
  return `var(${cssVarName})`
}

/**
 * Generate complete CSS stylesheet for a palette
 * @param palette - Color palette
 * @param paletteName - Name of the palette for CSS class
 * @returns CSS string
 */
export function generateCSSStylesheet(
  palette: ColorPalette,
  paletteName: ColorPaletteName
): string {
  const variables = generateCSSVariables(palette)
  const cssProperties = Object.entries(variables)
    .map(([property, value]) => `  ${property}: ${value};`)
    .join('\n')

  return `
:root[data-color-palette="${paletteName}"],
.palette-${paletteName} {
${cssProperties}
}

/* Utility classes for ${paletteName} palette */
.palette-${paletteName} .bg-theme-primary { background-color: ${getCSSVar('background.primary')}; }
.palette-${paletteName} .bg-theme-secondary { background-color: ${getCSSVar('background.secondary')}; }
.palette-${paletteName} .bg-theme-surface { background-color: ${getCSSVar('surface.default')}; }
.palette-${paletteName} .text-theme-primary { color: ${getCSSVar('text.primary')}; }
.palette-${paletteName} .text-theme-secondary { color: ${getCSSVar('text.secondary')}; }
.palette-${paletteName} .text-theme-accent { color: ${getCSSVar('text.accent')}; }
.palette-${paletteName} .border-theme-default { border-color: ${getCSSVar('border.default')}; }
.palette-${paletteName} .border-theme-interactive { border-color: ${getCSSVar('border.interactive')}; }
`.trim()
}

/**
 * Create a complete CSS file with all palettes
 * @param palettes - All available palettes
 * @returns Complete CSS content
 */
export function generateCompleteCSSFile(
  palettes: Record<ColorPaletteName, ColorPalette>
): string {
  const stylesheets = Object.entries(palettes)
    .map(([name, palette]) => generateCSSStylesheet(palette, name as ColorPaletteName))
    .join('\n\n')

  return `
/**
 * GENERATED THEME CSS VARIABLES
 * 
 * This file is automatically generated from the color palette definitions.
 * Do not edit manually - regenerate using the theme system.
 */

${stylesheets}

/* Global theme utilities */
.theme-transition {
  transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;
}

.theme-transition * {
  transition: inherit;
}

/* Smooth transitions when switching palettes */
:root {
  transition: all 0.3s ease;
}
`.trim()
}

/**
 * Helper to batch apply multiple CSS custom properties
 * @param properties - Object with CSS property names and values
 */
export function batchApplyCSSProperties(properties: Record<string, string>): void {
  const root = document.documentElement
  
  // Use requestAnimationFrame to batch DOM updates
  requestAnimationFrame(() => {
    Object.entries(properties).forEach(([property, value]) => {
      root.style.setProperty(property, value)
    })
  })
}

/**
 * Remove all theme-related CSS variables
 */
export function clearThemeVariables(): void {
  const root = document.documentElement
  
  // Get all style properties and filter theme variables
  const themeProperties = Array.from(root.style).filter(prop => 
    prop.startsWith(`--${CSS_VAR_PREFIX}-`)
  )
  
  // Remove theme variables
  themeProperties.forEach(prop => {
    root.style.removeProperty(prop)
  })
}

/**
 * Get current value of a CSS variable
 * @param path - Dot notation path to the color
 * @returns Current CSS variable value or empty string
 */
export function getCurrentCSSVarValue(path: string): string {
  const cssVarName = `--${CSS_VAR_PREFIX}-${path.replace(/\./g, '-')}`
  return getComputedStyle(document.documentElement).getPropertyValue(cssVarName).trim()
}

/**
 * Check if a specific palette is currently active
 * @param paletteName - Name of the palette to check
 * @returns True if the palette is active
 */
export function isColorPaletteActive(paletteName: ColorPaletteName): boolean {
  return document.documentElement.getAttribute('data-color-palette') === paletteName
}

/**
 * Set the active color palette on the document element
 * @param paletteName - Name of the palette to activate
 */
export function setActiveColorPalette(paletteName: ColorPaletteName): void {
  document.documentElement.setAttribute('data-color-palette', paletteName)
}